trigger:
- master

pool: batuhan-local

steps:

- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    fortifyBuildId: 'php'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'ssc test'
    fortifyApplicationName: 'hackigniter'
    fortifyApplicationVersion: '1'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $fortify_ssc_api_url = "http://192.168.13.76:8081/ssc/api/v1/projectVersions/10001/issues?start=0&limit=200&q=%5Bfortify%20priority%20order%5D%3Acritical&qm=issues&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false"
      $token = "FortifyToken NGMxN2EwZGItMzBmZS00OTAwLTkwYjgtNDY2YTMwYTlkN2Vm"
      
      $headers = @{
          "Authorization" = $token
          "Content-Type" = "application/json"
          "Accept" = "application/json"
      }
          # Api request get
          $response = Invoke-WebRequest -Uri $fortify_ssc_api_url -Method Get -Headers $headers
              $project_versions_data = $response.Content | ConvertFrom-Json
                if($project_versions_data.count -ge 30){
                Write-Host "Pipeline Broken. Error Status: Exit Code 1"
                Exit 1
                }
                return $project_versions_data.count
