trigger:
- master

pool: Default

steps:

- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    fortifyBuildId: 'php'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'ssc test'
    fortifyApplicationName: 'hackigniter'
    fortifyApplicationVersion: '1'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $fortify_ssc_api_url = "http://192.168.13.76:8081/ssc/api/v1/projectVersions/10001/issues?start=0&limit=200&q=%5Bfortify%20priority%20order%5D%3Acritical&qm=issues&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false"
      $token = "FortifyToken NGMxN2EwZGItMzBmZS00OTAwLTkwYjgtNDY2YTMwYTlkN2Vm"
      
      $headers = @{
          "Authorization" = $token
          "Content-Type" = "application/json"
          "Accept" = "application/json"
      }
      
      try {
          # Api request get
          $response = Invoke-WebRequest -Uri $fortify_ssc_api_url -Method Get -Headers $headers
      
          # Reponse status
          if ($response.StatusCode -eq 200) {
              # JSON data parse
              $project_versions_data = $response.Content | ConvertFrom-Json
      
              # Json data write
              $file_path = "C:\Users\Administrator\Desktop\test.json"
              $project_versions_data | ConvertTo-Json -Depth 4 | Out-File -FilePath $file_path
              $jsonData = Get-Content "C:\Users\Administrator\Desktop\test.json"
              $priorityLines = $jsonData | Where-Object { $_ -like "*friority*" }
              $txtFile = "C:\Users\Administrator\Desktop\output.txt"
              $priorityLines | Out-File -FilePath "C:\Users\Administrator\Desktop\output.txt"
      
      
              Write-Host "Project vulnerability info export succes."
          } else {
              throw "HTTP Error: $($response.StatusCode) $($response.StatusDescription)"
          }
      } catch [System.Net.WebException] {
          Write-Host "HTTP Error: $($_.Exception.Message)"
      } catch {
          Write-Host "An error occurred: $($_.Exception.Message)"
      }

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $content = Get-Content -Path "C:\Users\Administrator\Desktop\output.txt"
      $x = 2
      
      $lines = $content | Where-Object { $_ -like "*friority*" }
      
      if ($lines.Length -ge $x) {
           Write-Host "proccess killed."
          Exit 1
         
      }