trigger:
- master

pool: Default

steps:

- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    fortifyBuildId: 'php'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'ssc test'
    fortifyApplicationName: 'hackigniter'
    fortifyApplicationVersion: '1'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $fortify_ssc_api_url = "$(url)"
            $token = "FortifyToken $(FortiToken)"
      
            $headers = @{
              "Authorization" = $token
              "Content-Type" = "application/json"
              "Accept" = "application/json"
            }
      
            try {
              
              $response = Invoke-WebRequest -Uri $fortify_ssc_api_url -Method Get -Headers $headers
      
              
              if ($response.StatusCode -eq 200) {
                
                $project_versions_data = $response.Content | ConvertFrom-Json
      
                
                $priorityLines = $project_versions_data | Where-Object { $_ -like "*friority*" }
      
                
                if ($priorityLines.Length -ge 2) {
                  Write-Host "Pipeline Broken. Error Status: Exit Code 1"
                  Exit 1
                }
      
                
              }
            } catch {
             
            }