trigger:
- master

pool: Default

steps:

- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    fortifyBuildId: 'php'
    fortifyScanType: 'LocalScan'
    runFortifyUpload: true
    fortifyServerName: 'ssc test'
    fortifyApplicationName: 'hackigniter'
    fortifyApplicationVersion: '1'


- powershell: |
    $fprOutput = fprutility -information -search -query "[fortify priority order]:low" -project C:\agent\_work\3\a\sca_artifacts\php.fpr
    if ($fprOutput -contains "of") {
      exit 1
    }